version: "3.9"

services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - saoviet-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - saoviet-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saoviet-main-app:0.0.1
    container_name: main
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - saoviet-network
    depends_on:
      - mysql
      - rabbitmq

volumes:
  db_data:
    name: saoviet-db-data

networks:
  saoviet-network:
    name: saoviet-network
    driver: bridge
