export const ROUTERS = {
    USER: {
        HOME: "",
        LOGINPAGE: "auth/login",
        REGISTERPAGE: "auth/register",
        PROFILE: "customer/infor",
        PASSWORD: "customer/password",
        NEWS: "news/index",
        NEWSDETAIL: "news/detail/:id",
        TOUR: "tour/index",
        TOURCATEGORY: "tour/category",
        TOURLIST: "tour/category/:id",
        TOURDETAIL: "tour/detail/:id",
        BOOKING: "booking/:id",
        BOOKINGMESSAGE: "booking/message",
        CALENDAR: "/calendar/index",
        CALENDARDETAIL: "/calendar/detail/:id",
        SEARCH: "/tour/search",
        SEARCHDESTINATION: "/tour/search-destination",
        ACTIVATE: "/customer/activate/:id",
        ABOUT: "/about",
        DESTINATIONS: "/destinations/index",
    },
    ADMIN: {
        LOGINPAGE: "/manage/auth/login",
        CUSTOMERPAGE: "/manage/customers",
        TOURPAGE: "/manage/tours/index",
        TOURINSERTPAGE: "/manage/tours/insert",
        TOURUPDATEPAGE: "/manage/tours/edit/:id",
        SCHEDULEPAGE: "/manage/schedules",
        SCHEDULEINSERTPAGE: "/manage/schedules/insert",
        CALENDARPAGE: "/manage/calendars",
        CALENDARDETAILSPAGE: "/manage/calendars/detail/:id",
        PROFILEPAGE: "/manage/infor",
        PASSWORDPAGE: "/manage/password",
        DASHBOARDPAGE: "/manage/dashboard",
        PROMOTIONPAGE: "/manage/promotions",
        PROMOTIONUPDATEPAGE: "/manage/promotions/edit/:id",
        PROMOTIONINSERTPAGE: "/manage/promotions/insert",
        NEWSPAGE: "/manage/news",
        NEWSINSERTPAGE: "/manage/news/insert",
        NEWSUPDATEPAGE: "/manage/news/edit/:id",
    },
    ERROR: {
        ERROR500: '/error/500',
        MANAGEERROR500: '/manage/error/500',
    },
}